### PR TITLE
Add profiles.yaml.tmpl file as a reference

### PR DESCRIPTION
**Pull request by fkoksal**

### CODE REVIEW

**Review by vst — CHANGES_REQUESTED** [review]
1. Can you rebase?
2. Can we add a new sub-command to decafcli (main application) `example-profiles` that produces the `profiles.yaml` content with ALL types of DECAF credentials? We can then produce the `profiles.yaml.tmpl` using this sub-command.

**Review by vst — APPROVED** [review]

**Review by vst — CHANGES_REQUESTED** [review]
A few notes:

- [x] The command does not need any options. We can leave out the `--file-profiles` option.
- [x] The command should `exitSuccess` instead of `exitFailure`.
- [x] We can add one more example for Token authentication for completeness (I know, it does make little sense).
- [x] We already depend on `yaml` in the library. We can use `yaml` instead of `aeson-yaml`.
- [x] When printing the output, use `B.putStr` instead of `print`.

**Comment by fkoksal** [comment]
Should be OK, now.

**Review by vst — APPROVED** [review]

**Review by vst — APPROVED** [review]
:+1: It looks fine.

But we may need to squash this PR as the commit history looks funny. Let's see together.

**Pull request merged**
